### ISSUE TITLE
Event Registration Template

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#10]
## Event Details

**Title of the Brainhack Organization (e.g. Brainhack Marburg):**

**Title of the Event:**

**Description of the Event:**

**Date of the Event:**

**Link to the specific event page (if exists):**

**Online meeting link:** 

**Contact Information Regarding Queries:**

**Main Mattermost Communication Channel for Your Local Event**

## Event Labeling
- [ ] Expected Profile of the Event Audience  
- [ ] Event Type: 
- [ ] Event label (e.g. brainhack_Marburg)

- [ ] Event snippet for the Brainhack website

**Comment by SamGuay** [comment]
Is this template for the google form or for an _event_ template issue like the project one? @complexbrains

**Comment by jhlegarreta** [comment]
I think having made available the google form for local organizers to register to host an event makes this template unnecessary/edundant. Closing.
