### ISSUE TITLE
What to do with sh***y (clinical) data? How to apply your perfect estimator/model/method to data that contains outliers? 

### ISSUE THREAD

**Issue by vilsaira** [brainhackorg/global2020#106]
## Project info

**Title:** What to do when (clinical) Diffusion Weighted Image data quality is sh***y: How to adjust for it in modeling and estimate the confidence of your model afterward?

**Project lead:** Viljami Sairanen [Twitter @ViljamiSairanen](https://twitter.com/viljamisairanen)

**Project collaborators:** 

**Registered Brainhack Global 2021 Event:** Brainhack Atlantis The Atlantic Ocean - Micro2Macro

**Project Description:**

**1 Aim:** Modify existing brain structure modeling algorithms and estimators to adjust for outliers in the measurements to enable their usage in clinical neuroresearch. The aim is to publish the results as a journal article.

**2 Reason:** Clinical data is often corrupted by outliers and artifacts from various sources (e.g. subject motion shown if **Fig.1**).
![image](https://user-images.githubusercontent.com/28725251/105063033-8db72780-5a7b-11eb-802b-f84c1e3a5e06.png)
**Fig. 1** _Visualization of the differences between the cutting-edge research data of the Human Connectome Project and clinical patient data of a neonatal subject. A) A sagittal slice of a DW-MRI data from an HCP subject and B) an axial slice from the same HCP subject are only slightly affected by noise thus being easy to process with any modeling algorithm. C) A sagittal slice of a DW-MRI data from a clinical neonatal subject with the red arrow pointing to two adjacent axial slices in D) showing a good quality slice and E) showing missing data error due to subject motion. This clinical example is a very common case of suboptimal image quality in neonatal imaging projects or other projects with uncooperative patients and subjects. Therefore, processing steps developed using data primarily from sources with excellent quality could result in highly inaccurate connectome models when applied to clinical data._

**3 How:** A highly realistic ground-truth simulation of diffusion-weighted image (DWI) set of the human brain structures is shared with the participants. Simulation is based on the Human Connectome Project data and is generated using MRTrix3 and COMMIT framework. A Python script is provided to introduce the outliers and realistic noise distribution to the ground-truth dataset for algorithm evaluation purposes. The simulated dataset will be sent directly to the participants as the HCP data (which this quite directly is) should not be hosted outside their original repository.

Participants can either propose their own algorithms to be evaluated with this data or completely new estimation algorithms can be proposed. Finally, the best algorithms will be compared with real human data acquired from neonatal subjects that contain typical motion artefacts. This data cannot be shared with the participants due to the sensitive nature of data. The acquisition consists of multiple reference b0 images and two shells on (60 DWIs with b-value of 750 and 74 with b-value of 1800).

**Data to use:**  A highly realistic synthetic diffusion-weighted MRI dataset is shared with the participants here:  <link removed>

**Link to project repository/sources:** Code resources will be shared here <link removed>. Notably, the dataset is too large for GitHub.

**Goals for Brainhack Global 2020:** Evaluation of multiple robust microstructural models or DWI signal representations with the provided data. Results would be published in a peer-review journal and as a conference abstract (if suitable).

**Good first issues:**
 1. Selecting which model estimators will be used in this project (tensors, csd, noddi, etc.).
 2. Implementing the robust augmentations in each estimator.
 3. Comparing both the original and the robust estimator with the synthetic dataset.
 4. Optional comparison with the clinical neonatal data.

**Skills:** 
OS: Any
Probably necessary: Python or Matlab, understanding of NIFTI or other neuroimage formats
Likely useful: shell scripting, MRTrix3, COMMIT
Definitely appreciated: consistent writing skills both in code and manuscript

**Tools/Software/Methods to Use:** Visual Studio Code, Python, Matlab, MRTrix3, COMMIT

**Communication channels:**
https://mattermost.brainhack.org/brainhack/channels/brainhack-micro2macro-2020
https://mattermost.brainhack.org/brainhack/channels/brainhack-micro2macro-robust-applications

Zoom

 

**Project labels**
#bhg:micro2macro_gbr_1

- Type of project:
#coding_methods, #method_development

- Project development status:
#1_basic structure, #2_releases_existing

- Topic of the projet:
#diffusion, #MR_methodologies, #reproducible_scientific_methods, #statistical_modelling, #tractography

- Tools used in the project:
#DIPY, #Freesurfer, #MRtrix, #Nipype, #SPM

- Tools skill level required to enter the project (more than one possible):
#familiar, #no_skills_required

- Programming language used in the project:
#Matlab, #Python, #R, #shell_scripting, #Unix_command_line

- Modalities involved in the project (if any):
#DWI, #MRI

- Git skills reuired to enter the project (more than one possible):
#0_no_git_skills, #1_commit_push, #2_branches_PRs

- [x] I added all of the labels I want an associate to my project

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [x] Link to your project: could be a code repository, a shared document, etc.
- [x] Goals for Brainhack Global 2020: describe what you want to achieve during this brainhack.
- [x] Flesh out at least 2 “good first issues”: those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document.
- [x] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill. Use the issue labels for this purpose.
- [x] Chat channel: A link to a chat channel that will be used during the Brainhack Global 2020 event. This can be an existing channel or a new one. We recommend using the [Brainhack space on Mattermost](https://mattermost.brainhack.org/).

Optionally, you can also include information about:

- [ ] Number of participants required.
- [ ] Twitter-sized summary of your project pitch.
- [ ] Provide an image of your project for the Brainhack Global 2020 website. 

We would like to think about how you will credit and onboard new members to your project. If you’d like to share your thoughts with future project participants, you can include information about:

- [ ] Specify how you will acknowledge contributions (e.g. listing members on a contributing page).
- [ ] Provide links to onboarding documents if you have some:

**Comment by complexbrains** [comment]
Dear @vilsaira Thank you very much for submitting your project! 🎉 

May I ask you to complete those several questions please then the issue will be ready to be published.
- Data to use
- Link to project repository/sources
- Good first issues
- Tools/Software/Methods to Use

Also please put the # in front of the tagging words that you think related to your project to have them as labels for the audience to identify your project better. Similarly, please share an image with us (by putting in the issue somewhere) that you think that represents your project if you do not want to use the one you already provided. Then I will create the card for your project and list in the Brainhack webpage. 

Please let me know if you need help with anything! Looking forward to your project! 🤗

**Comment by vilsaira** [comment]
Thanks @complexbrains! I updated the project according to the suggestions. Hopefully, it is now sufficient.

**Comment by complexbrains** [comment]
@vilsaira Fantastic 💯 Let's get your project take its place among the others! Liking the name btw 🙃 I feel the pain! 😏 

Enjoy your participation in the event. And let us know with anything we can help with 🤗

**Comment by complexbrains** [comment]
Dear @vilsaira I saw you closed your issue, which is totally fine. However I just wanted to tell you, having your project listed among other issues might be beneficiary for yourself for the future purposes if you would like that would help you to advertise your project and your contributions throughout the event. However sure that we will still be having it listed in our [webpage](https://brainhack.org/global2020/projects/) so it is totally up to you. I just wanted to raise your attention to it back again. 

Thank you for your participation to the event and hope you enjoyed it so far 🤗
