### ISSUE TITLE
Mattermost/Jitsi/Zoom Tutorials for the Beginners

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#17]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
Creating an easy and quick tutorial for the use of the Mattermost/Jitsi/Zoom
The plan would be to:
  1. Simple tutorials regarding the basic and most important features starting from how to create a user/meeting/, attend to a channel/event/meeting.

* **Other info**:

**Comment by SamGuay** [comment]
Closed this, but still available [here](https://github.com/brainhackorg/global2020/projects/1)
