### ISSUE TITLE
Project submission instructions

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#18]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
Instructions regarding how to use the project submission issue
The plan would be to:
  1. A quick instruction guideline regarding how to submt/review a project, assign the correct labels, and the workflow regarding the approval procedure.  

* **Other info**: 
Have dependencies on the completion of the 
-  project submission workflow

**Comment by jhlegarreta** [comment]
Available here: https://brainhack.org/global2020/projects/ (towards the end of the page)

Closing the issue.
