### ISSUE TITLE
Instructions for the use of the Calendar Viewing/Listing

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#19]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
Instructions regarding how to use the Calendar Viewing/Listing
The plan would be to:
  1. A quick instruction guideline regarding how to submit an event into the calendar view, synchronization of it with their calendar choice of interest, and the approval procedure.  

* **Other info**: 
Have dependencies on the completion of the 
-  calendar view workflow

**Comment by SamGuay** [comment]
Closed this, but still available [here](https://github.com/brainhackorg/global2020/projects/1)
