### ISSUE TITLE
Instructions for the use of the Matching Algorithm

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#20]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
Instructions regarding how to use the Matching Algorithm
The plan would be to:
  1. A quick instruction guideline regarding how to the matching algorithm will work and how participants should benefit from it.  

* **Other info**: 
Have dependencies on the completion of the 
-  matching algorithm workflow

**Comment by SamGuay** [comment]
Closing this as #23 is open and is about the matching algo.
