### ISSUE TITLE
Quick Virtual Event Organizing /Participation Guidelines 

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#21]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
Using the main guideline, extracting the associated sections as markdown pages in the Github repo. 
The plan would be to:
  1. @complexbrains will condense the guideline into a shorter version
  2.  The sections will be converted into separate Md pages. 

* **Other info**:

**Comment by SamGuay** [comment]
Closed this, but still available [here](https://github.com/brainhackorg/global2020/projects/1)
