### ISSUE TITLE
Project Spec - Skill Set Matching Algorithm

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#23]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
A workflow in for the matching algorithm to deploy on the webpage using the skills ticked by the participants in the [registration form](https://docs.google.com/forms/d/1dCy9NpprAtd1gZU6FBrvpSX9WwAGS54U_r7pLTiHScI/edit) of a local event site and matching the [labels](https://docs.google.com/spreadsheets/d/1mbc9mcT0o27oECNhEnErS16QQ2dT3BKjSvOe_UaRgYs/edit#gid=1327314525) chosen for the projects based on a ranking (best match) and listing the first 3 best options based on the fields the participants would like to work on. 

The plan would be to:
  1.  Deciding on the algorithm itself
  2.  Deciding on how to run the workflow (where to deploy, who to run)

Opt1. Local organizers extract the participant skillsets themselves, enter the skillset + participant's email to the algorithm on the Brainhack 2020 webpage, the result is sent automatically to the participant himself/herself with the related info. 

3. In the case of the opt1 is agreed, needs to deciding on a dedicated page/link at the Brainhack 2020 webpage and email content to be sent. 

* **Other info**:

**Comment by jhlegarreta** [comment]
Closing. Being developed in https://github.com/brainhackorg/brainmatch
