### ISSUE TITLE
Virtual CoC Menu and Content

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#3]
Here is the latest version of the [Virtual CoC](https://docs.google.com/document/d/11aE6vv67i9pzOUN7DTypqiAVUutXAijP7_jZTURHhAM/edit?usp=sharing) that requires to be organized well. The content will be replaced with the oldest content [here](http://www.brainhack.org/code-of-conduct.html) and will be given a link either in the landing page or as a subpage.

**Comment by complexbrains** [comment]
@SamGuay and @complexbrains worked on it to the latest version to be shared with the whole BHG team, which is [here](https://docs.google.com/document/d/11aE6vv67i9pzOUN7DTypqiAVUutXAijP7_jZTURHhAM/edit)

Standing issues

- Could we replace it with the current [Code of Conduct](https://brainhack.org/code-of-conduct.html) on the main Brainhack webpage?
- Can we have a team of volunteers from the Community and outside of the Brainhack global organizers to work on the violations of the Code of Conduct by the main local event organizers and other exceptional situations?

- Can we have a dedicated email address dedicated to communicating with this particular team in private?

**Comment by SamGuay** [comment]
Will close this issue for now as the page is online.
