### ISSUE TITLE
Incorrect link to Brainhack Donostia organization in GitHub

### ISSUE THREAD

**Issue by eurunuela** [brainhackorg/global2020#30]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] design request

* **What is the current behavior? / What feature/design would you like to implement**
The website shows the old (incorrect) Brainhack Donostia organization in GitHub.

* **What is the expected behavior?**
It should link to [this one](https://github.com/Brainhack-Donostia).

**Comment by sofievdbos** [comment]
PR #31 has been merged to solve this issue. 😄 
Can you confirm @eurunuela?

**Comment by eurunuela** [comment]
> PR #31 has been merged to solve this issue. 😄
> Can you confirm @eurunuela?

Thank you so much Sofie! It's correct now 🙌🏻
