### ISSUE TITLE
Host a Local Event Menu

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#4]
A menu that allows registration of the local events via [this form](https://docs.google.com/forms/d/1kAmy_yc9V7PJkriVZVCr-MH-jCh3AAmy4hKHvpvC5cQ/edit). Whether present it as an embedded form or give a link remains to be discussed.

**Comment by complexbrains** [comment]
The form is brought to the latest version and ready to the implementation in the webpage @SamGuay

**Comment by jhlegarreta** [comment]
The form is already available:
https://brainhack.org/global2020/events/#host-a-local-brainhack

I assume it is the right form. Shall we close this issue?

**Comment by SamGuay** [comment]
That is correct, I was waiting on merging the same branch to close it, but will close it now.
