### ISSUE TITLE
Trial for labels

### ISSUE THREAD

**Issue by bhg-donostia** [brainhackorg/global2020#43]
## Project info

**Title:**

Double-checking if the auto labeling works
**Project lead:**

**Project collaborators:**

**Registered Brainhack Global 2020 Event:**

**Project Description:**

**Data to use:**

**Link to project repository/sources:**

**Goals for Brainhack Global 2020:**

**Good first issues:**

1.
2.

**Skills:**

**Communication channels:**

 

**Project labels**

- [ ] I added all of the labels I want associate to my project

### Submission checklist

*Once the issue is submitted, please check items in this list as you add under ‘Additional project info’*

- [ ] Link to your project: could be a code repository, a shared document, etc.
- [ ] Goals for Brainhack Global 2020: describe what you want to achieve during this brainhack.
- [ ] Flesh out at least 2 “good first issues”: those are tasks that do not require any prior knowledge about your project, could be defined as issues in a GitHub repository, or in a shared document.
- [ ] Skills: list skills that would be particularly suitable for your project. We ask you to include at least one non-coding skill. Use the issue labels for this purpose.
- [ ] Chat channel: A link to a chat channel that will be used during the Brainhack Global 2020 event. This can be an existing channel or a new one. We recommend using the [Brainhack space on Mattermost](https://mattermost.brainhack.org/).

Optionally, you can also include information about:

- [ ] Number of participants required.
- [ ] Twitter-size summary of your project pitch.
- [ ] Provide an image of your project for the Brainhack Global 2020 website. 

We would like to think about how you will credit and onboard new members to your project. If you’d like to share your thoughts with future project participants, you can include information about:

- [ ] Specify how you will acknowledge contributions (e.g. listing members on a contributing page).
- [ ] Provide links to onboarding documents if you have some:

**Comment by smoia** [comment]
@SamGuay if this works, we can close the issue.
