### ISSUE TITLE
Organizers/Team

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/global2020#7]
Main organizers and contributors to be listed on the webpage similar to listing in [BHS webpage](https://school.brainhackmtl.org/) if everyone is ok with?

**Comment by sofievdbos** [comment]
I'll work on this one. But I'm not able to self-assign...

**Comment by complexbrains** [comment]
@sofievdbos Please do not forget to add the Donostia team as a sublisting was done in the OHBM Brainhack page https://ohbm.github.io/hackathon2020/team/ but the style will be as in BHS webpage.  I guess you might want to ask the Donostia team who should be listed there. Since some are not in the chat group still works in the background to help us.

**Comment by complexbrains** [comment]
@smoia could you give us a list of organizers/volunteers and their Github/twitter accounts and if they do not have a GitHub could you provide some images somewhere secure please so we can work on that?

**Comment by smoia** [comment]
@complexbrains do you mean people that helped in the BHG or the full organising team of the BH Donostia? In the latter case, this is the list: https://brainhack-donostia.github.io/about/

**Comment by sofievdbos** [comment]
The core framework to add the Team is ready. For now, I created two categories: **BHG 2020 Core Team** & **Volunteers** (where I would list the Donostia team who've helped in the BHG 2020). Were those the subcategories you had in mind? In that way, others who might reach out to volunteer can also be listed under the **Volunteers** section. However, feel free to suggest other options/names/subcategories!! 😀 Happy to change however you would like @smoia @complexbrains!  

What we list for now: 
* **required**: an avatar image (grabbed from GitHub account), name + surname
* **optional**: social (email, Twitter, GitHub), when hovering over the image: position (e.g. PhD candidate at ...)

**Comment by complexbrains** [comment]
Thank you, Sofie. 
I guess it would be better to keep the naming of the team the same as we used it in our emails, documents and in many other places which is "Brainhack Global Organizing Committee". I believe Volunteers should be fine. 

We might also need a Code of Conduct team, if we can manage helpers, buddies but those are not certain yet, so let's leave it as those two now.

**Comment by sofievdbos** [comment]
> "Brainhack Global Organizing Committee"

Good point! Thanks! 🙏 

> Code of Conduct team

Creating a new subcategory is very easy! So whenever we want to add one, we can do so! 😀

**Comment by smoia** [comment]
Going back to the volunteers from BHD that did something specific (contributing with ideas/meetings/items/...) for BHG, if you don't want to list the whole BHD team, they are:
- @afurgoni20 (Alberto Furgoni)
- @danalclop (Daniel Alcalá)
- @eurunuela (Eneko Uruñuela)
- @smoia (Stefano Moia TW: `@SteMoia`) 

@eurunuela @danalclop @afurgoni20 please write your twitter handle if you have one!

**Comment by eurunuela** [comment]
Thank you for this guys!

My Twitter handle is [@eurunuela](https://twitter.com/eurunuela) just like the GH one. 

Do you need my personal website or my email too?

**Comment by sofievdbos** [comment]
Created a PR #29 --> If you would like me to change or add something, let me know! 😀 --> e.g. if you would like another (non-GitHub) avatar image, if you would like to add your email address and/or Twitter handle!

**Comment by jhlegarreta** [comment]
PR #29 has been merged, so closing the issue. Thanks @sofievdbos !
