### ISSUE TITLE
TR-OPEN "getting started", Introducing Open Ethical Committee Permissions as an introductory step of open science

### ISSUE THREAD

**Issue by mselimata** [brainhackorg/global2020#78]
Brainhack Ankara Project For Introducing Open Ethical Committee Permissions as an introductory step of open science. Goal is to create a resource for researchers in Turkey to start public sharing data. We would be compiling examples for applications to ethical committees, *examples of language in informed consent, list of universities and ethical committees that have approved public data sharing, resources and links to relevant regulations.

**Comment by complexbrains** [comment]
Dear @i-am-mel-dev thank you very much for this amazing project. Would you like to fill our project submission template in [here](https://github.com/brainhackorg/global2020/issues/new/choose) following the guideline inside the template so we can have a dedicated page of the project under Brainhack webpage and lists the project amoung others please? https://brainhack.org/global2020/projects/ Looking forward to your issue 🤗

**Comment by mselimata** [comment]
Thank you @complexbrains thanks for providing a comprehensive guideline, I tried to fill as much as I could with the help of the project lead @mariaveldhuizen , feel free to close this issue to prevent further confusion.

**Comment by complexbrains** [comment]
Hi @i-am-mel-dev Perfect! will close this issue since we have #80 for the same project!
